CREATE TABLE admins
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_admin PRIMARY KEY (id)
);

INSERT INTO admins (email, password) VALUES ('admin@eurder_db.com', '$2a$12$r3fLIlWCAzvA6qgIqf.60uDPFn00QwpS6ba28LNvSXBYF0eHbVDAW');