CREATE TABLE items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    description     VARCHAR(255),
    price_id        BIGINT,
    amount_in_stock INTEGER,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

ALTER TABLE items
    ADD CONSTRAINT uc_item_price UNIQUE (price_id);

ALTER TABLE items
    ADD CONSTRAINT FK_ITEM_ON_PRICE FOREIGN KEY (price_id) REFERENCES prices (id);